# Generated by Django 3.2.4 on 2021-06-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=2)),
                ('genero', models.CharField(max_length=1)),
                ('id_agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.agencia')),
            ],
            options={
                'verbose_name_plural': 'aspirantes',
            },
        ),
        migrations.AlterModelOptions(
            name='profesion',
            options={'verbose_name': 'profesion', 'verbose_name_plural': 'profesiones'},
        ),
        migrations.CreateModel(
            name='Empleabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.aspirante')),
                ('id_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.oferta')),
            ],
            options={
                'verbose_name_plural': 'empleabilidad',
            },
        ),
        migrations.AddField(
            model_name='aspirante',
            name='id_profesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.profesion'),
        ),
    ]
