# Generated by Django 3.2.4 on 2021-06-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_aspirante_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='numero_cedula',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
