# Generated by Django 3.2.4 on 2021-06-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_aspirante_numero_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='descrpcion',
            new_name='descripcion',
        ),
    ]
