# Generated by Django 3.2.4 on 2021-06-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_remove_oferta_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='genero',
        ),
        migrations.AddField(
            model_name='aspirante',
            name='genero_choices',
            field=models.CharField(choices=[('f', 'f'), ('m', 'm')], default='m', max_length=1),
        ),
    ]
