# Generated by Django 3.2.4 on 2021-06-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_auto_20210629_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='genero_choices',
            field=models.CharField(choices=[('f', 'f'), ('m', 'm')], max_length=1),
        ),
    ]
