# Generated by Django 3.2.4 on 2021-06-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_aspirante_genero_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspirante',
            old_name='genero_choices',
            new_name='genero',
        ),
    ]
