# Generated by Django 3.2.4 on 2021-06-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_alter_aspirante_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion',
            name='nombre',
            field=models.CharField(choices=[('Abogado', 'Abogado'), ('I. Sistemas', 'I. Sistemas'), ('A. Empresas', 'A. Empresas'), ('Psicólogo', 'Psicólogo')], max_length=20),
        ),
    ]
